In [2]:
import numpy as np
import theano
import theano.tensor as T

In [10]:
spikes1 = T.vector("spikes1")
spikes2 = T.vector("spikes2")
spikes_merged = T.vector("spikes_merged")

merge_spikes = theano.function([spikes1, spikes2], T.clip(spikes1.dimshuffle(0, 'x') + spikes2, 0, 1))

In [11]:
spikesA = np.random.rand(10) > 0.75
spikesB = np.random.rand(10) > 0.75
merged = merge_spikes(spikesA, spikesB)

print spikesA, spikesB
print merged

[ True False False False False False False False False False] [False  True False False False False False False False  True]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]]
